import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import SiteHeader from "../../components/SiteHeader";
import SiteFooter from "../../components/SiteFooter";
import { PublicContactLinks } from "../../components/ExternalLinks";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { createClient } from "@/lib/supabase/server";
import { companyInitials, productMark, sampleCompanies, sampleProducts, type PublicCompany, type PublicProduct } from "@/lib/marketplace";
export const dynamic="force-dynamic";
async function loadCompany(id:string){const sampleIndex=id.startsWith("sample-")?Number(id.replace("sample-",""))-1:-1;if(sampleIndex>=0)return{company:sampleCompanies[sampleIndex]??null,products:sampleProducts.slice(0,3)};if(!isSupabaseConfigured())return{company:null,products:[]};const supabase=await createClient();let {data:company}=await supabase.from("public_company_directory").select("id,user_id,company_name,business_type,city,province,district,tehsil,address,description,website,contact_email,public_phone,google_maps_url,logo_url").eq("id",id).maybeSingle();if(!company){const legacy=await supabase.from("public_company_directory").select("id,user_id,company_name,business_type,city,province,district,tehsil,address,description,website,contact_email,public_phone,google_maps_url,logo_url").eq("user_id",id).maybeSingle();company=legacy.data}if(!company)return{company:null,products:[]};const filters=[`company_id.eq.${company.id}`];if(company.user_id)filters.push(`company_user_id.eq.${company.user_id}`);const {data:products}=await supabase.from("products").select("*").or(filters.join(",")).eq("verification_status","approved").eq("is_published",true).order("created_at",{ascending:false});const publicProducts=(products??[]).map((r):PublicProduct=>({id:r.id,slug:r.slug,product_name:r.product_name,brand_name:r.brand_name,generic_name:r.generic_name,category:r.category,sector:r.sector,composition:r.composition,strength:r.strength,dosage_form:r.dosage_form,pack_sizes:r.pack_sizes??[],indications:r.indications,description:r.description,storage_instructions:r.storage_instructions,image_url:r.image_url,availability:r.availability,product_code:r.product_code,subclass:r.subclass,therapeutic_class:r.therapeutic_class,sectors:r.sectors??[],species:r.species??[],production_systems:r.production_systems??[],use_areas:r.use_areas??[],routes:r.routes??[],precautions:r.precautions,contraindications:r.contraindications,warnings:r.warnings,meat_withdrawal:r.meat_withdrawal,milk_withdrawal:r.milk_withdrawal,egg_withdrawal:r.egg_withdrawal,cold_chain:r.cold_chain,temperature_range:r.temperature_range,shelf_life:r.shelf_life,country_of_origin:r.country_of_origin,regulatory_review_status:r.regulatory_review_status,company_user_id:company.user_id,company_id:company.id,company_name:company.company_name,company_city:company.city}));return{company:company as PublicCompany,products:publicProducts}}
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const {company}=await loadCompany(id);if(!company)return{title:"Veterinary Company"};return{title:`${company.company_name} | Veterinary Company Profile`,description:company.description||`${company.company_name} animal-health company profile on VetConnect Pakistan.`,alternates:{canonical:`/companies/${id}`},robots:company.is_sample?{index:false,follow:true}:undefined}}
export default async function CompanyDetailPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const {company,products}=await loadCompany(id);if(!company)notFound();return <main><SiteHeader/><section className="page-hero"><div className="shell company-profile-hero">{company.logo_url?<img className="company-profile-logo" src={company.logo_url} alt={`${company.company_name} logo`} loading="lazy" decoding="async"/>:<div className="company-mark company-profile-logo">{companyInitials(company.company_name)}</div>}<div><span className="section-kicker">{company.is_sample?"SAMPLE COMPANY":"VERIFIED COMPANY"}</span><h1>{company.company_name}</h1><p>{company.description||"A verified VetConnect animal-health company profile."}</p><div className="profile-chips"><span>{company.business_type||"Animal health"}</span><span>{company.city||"Pakistan"}</span></div></div></div></section><section className="section compact-section"><div className="shell company-contact-grid"><article><span>Location</span><b>{company.address||[company.tehsil||company.city,company.district,company.province].filter(Boolean).join(", ")||"Pakistan"}</b>{company.google_maps_url&&<PublicContactLinks mapUrl={company.google_maps_url}/>}</article><article><span>Public contact</span><PublicContactLinks phone={company.public_phone} email={company.contact_email}/></article><article><span>Website</span><PublicContactLinks website={company.website}/></article></div></section><section className="section section-soft"><div className="shell"><div className="section-heading"><span className="section-kicker">APPROVED PRODUCTS</span><h2>Public company listings.</h2></div>{products.length===0?<div className="empty-state"><p>This company has no approved public products yet.</p><Link href="/marketplace">Browse marketplace</Link></div>:<div className="product-grid">{products.map(p=><article className="product-card" key={p.slug}><div className="product-visual">{productMark(p)}</div><span>{p.category}</span><h3>{p.product_name}</h3><p>{p.generic_name||p.brand_name||"Structured product listing"}</p><Link className="button button-primary button-full" href={`/marketplace/${p.slug}`}>View product</Link></article>)}</div>}</div></section><SiteFooter/></main>}
