import SiteHeader from "../components/SiteHeader";
import SiteFooter from "../components/SiteFooter";

const companies = [
  ["AH", "Animal Health Company", "Pharmaceuticals", "Lahore", "Medicines • Vaccines"],
  ["VN", "Veterinary Nutrition Company", "Feed & Nutrition", "Faisalabad", "Supplements • Feed Additives"],
  ["PC", "Poultry Solutions Company", "Poultry", "Lahore", "Products • Technical Services"],
  ["DC", "Dairy Solutions Company", "Dairy", "Multan", "Nutrition • Equipment"],
  ["AC", "Aquaculture Company", "Fisheries", "Karachi", "Feed • Health Products"],
  ["DX", "Veterinary Diagnostics Company", "Diagnostics", "Islamabad", "Laboratory • Kits"],
];

export default function CompaniesPage(){return <main><SiteHeader/><section className="page-hero"><div className="shell"><span className="section-kicker">COMPANY DIRECTORY</span><h1>Build a searchable animal-health business network.</h1><p>Company profiles provide the identity layer behind marketplace products, jobs, training partnerships and technical engagement.</p></div></section><section className="section compact-section"><div className="shell"><div className="directory-top"><div><b>Company profiles</b><span>Sample front-end directory</span></div><div className="market-search"><input placeholder="Search company"/><select><option>All business types</option><option>Pharmaceuticals</option><option>Feed</option><option>Equipment</option><option>Diagnostics</option></select></div></div><div className="company-grid">{companies.map(c=><article key={c[1]}><div className="company-mark large">{c[0]}</div><span className="sample-label">Sample company</span><h3>{c[1]}</h3><p>{c[2]} • {c[3]}</p><div className="profile-chips"><span>{c[4]}</span></div><dl><div><dt>Products</dt><dd>Structured listings</dd></div><div><dt>Jobs</dt><dd>Employer module</dd></div><div><dt>Contact</dt><dd>Profile-controlled</dd></div></dl><button className="button button-primary button-full">View company</button></article>)}</div></div></section><section className="section section-soft"><div className="shell two-col"><div><span className="section-kicker">BUSINESS PROFILE</span><h2>A single company identity across VetConnect.</h2><p>Once verified, the same business account can support product listings, job postings, company contacts, training partnerships and sector visibility without duplicating data.</p></div><div className="spec-list"><div><b>Identity</b><span>Registered name, NTN/registration, business type and locations.</span></div><div><b>Contacts</b><span>Website, social channels, city-wise contacts and authorized persons.</span></div><div><b>Marketplace</b><span>Products, categories, prices, delivery and documents.</span></div><div><b>HR & learning</b><span>Jobs, internships, technical courses and company participation.</span></div></div></div></section><SiteFooter/></main>}
