import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import SiteHeader from "../../components/SiteHeader";
import SiteFooter from "../../components/SiteFooter";
import ProfilePhoto from "../../components/ProfilePhoto";
import { PublicContactLinks } from "../../components/ExternalLinks";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { createClient } from "@/lib/supabase/server";
import { initials, sampleVeterinarians, type PublicVeterinarian } from "@/lib/directories";

export const dynamic = "force-dynamic";
async function loadVeterinarian(id:string):Promise<PublicVeterinarian|null>{ const sample=sampleVeterinarians.find(x=>x.user_id===id); if(!isSupabaseConfigured())return sample??null; const supabase=await createClient(); const select="user_id, full_name, qualifications, specialization, veterinary_sector, years_experience, city, province, district, tehsil, services, profile_verified, pvmc_verified, image_url, public_phone, contact_email, address, google_maps_url"; const a=await supabase.from("public_veterinarians").select(select).eq("user_id",id).maybeSingle(); if(a.data)return a.data as PublicVeterinarian; const m=await supabase.from("public_managed_veterinarians").select(select).eq("user_id",id).maybeSingle(); return (m.data as PublicVeterinarian|null)??null; }
export async function generateMetadata({params}:{params:Promise<{id:string}>}):Promise<Metadata>{const {id}=await params;const v=await loadVeterinarian(id);if(!v)return{title:"Veterinarian Profile"};return{title:`${v.full_name} | ${v.specialization||"Veterinarian"}`,description:`${v.full_name}, ${v.qualifications||"veterinary professional"}. ${v.specialization||"Veterinary services"} in ${v.city||"Pakistan"}.`,alternates:{canonical:`/vets/${id}`},robots:v.is_sample?{index:false,follow:true}:undefined};}
export default async function VeterinarianProfilePage({params}:{params:Promise<{id:string}>}){const {id}=await params;const v=await loadVeterinarian(id);if(!v)notFound();return <main><SiteHeader/><section className="page-hero"><div className="shell company-profile-hero"><div className="company-mark company-profile-logo profile-photo-frame"><ProfilePhoto imageUrl={v.image_url} name={v.full_name} fallback={initials(v.full_name)}/></div><div><span className="section-kicker">{v.is_sample?"SAMPLE PROFILE":"VERIFIED VETERINARIAN"}</span><h1>{v.full_name}</h1><p>{v.specialization||"Veterinary professional"}</p><div className="profile-chips">{v.qualifications&&<span>{v.qualifications}</span>}{v.veterinary_sector&&<span>{v.veterinary_sector}</span>}<span>{v.city||"Pakistan"}</span><span>{v.years_experience} years experience</span></div></div></div></section><section className="section compact-section"><div className="shell"><div className="feature-columns"><div><h3>Verification</h3><p><strong>PVMC credential:</strong> {v.pvmc_verified?"Verified":v.is_sample?"Sample only":"Pending"}</p><p><strong>VetConnect profile:</strong> {v.profile_verified?"Verified":v.is_sample?"Sample only":"Pending"}</p></div><div><h3>Professional information</h3><p><strong>Qualification:</strong> {v.qualifications||"Not specified"}</p><p><strong>Sector:</strong> {v.veterinary_sector||"Not specified"}</p><p><strong>Specialization:</strong> {v.specialization||"Not specified"}</p></div><div><h3>Location & contact</h3><p><strong>Location:</strong> {[v.tehsil||v.city,v.district,v.province].filter(Boolean).join(", ")||"Not specified"}</p>{v.address&&<p><strong>Address:</strong> {v.address}</p>}<PublicContactLinks phone={v.public_phone} email={v.contact_email} mapUrl={v.google_maps_url}/></div><div><h3>Services</h3>{v.services.length?<div className="profile-chips">{v.services.map(s=><span key={s}>{s}</span>)}</div>:<p>Services have not been listed.</p>}</div></div><div className="card-actions"><Link className="button button-primary" href="/clinics">Find clinic / appointment</Link><Link className="button button-secondary" href="/vets">Back to directory</Link></div></div></section><SiteFooter/></main>}
