import Link from "next/link";
import SiteHeader from "../components/SiteHeader";
import SiteFooter from "../components/SiteFooter";

const jobs = [
  ["Veterinary Officer", "Animal Health Company", "Lahore", "Livestock", "Full-time"],
  ["Technical Sales Executive", "Veterinary Nutrition Company", "Faisalabad", "Feed & Nutrition", "Full-time"],
  ["Poultry Veterinarian", "Poultry Company", "Lahore", "Poultry", "Full-time"],
  ["Veterinary Intern", "Clinical Practice", "Islamabad", "Pets", "Internship"],
  ["Quality Assurance Officer", "Animal Health Manufacturer", "Karachi", "Pharmaceutical", "Full-time"],
  ["Research Assistant", "Veterinary Research Project", "Multan", "Research", "Contract"],
];

export default function JobsPage() {
  return <main><SiteHeader /><section className="page-hero jobs-hero"><div className="shell"><span className="section-kicker">VETERINARY JOBS & TALENT</span><h1>Connect employers with the right veterinary talent.</h1><p>Designed for animal-health companies, clinics, farms, universities, research teams, NGOs, students and experienced professionals.</p><div className="hero-actions"><button className="button button-primary">Find jobs</button><button className="button button-secondary">Post a job</button></div></div></section>
    <section className="section compact-section"><div className="shell role-grid"><article><span className="module-tag">EMPLOYER / HR</span><h2>Recruitment workspace</h2><ul><li>Create a verified company/employer profile</li><li>Post jobs and internships by sector and city</li><li>Define qualification, experience and skill requirements</li><li>Search candidate profiles and CVs</li><li>Shortlist and track applications</li></ul><Link href="/register" className="button button-dark">Register as employer</Link></article><article><span className="module-tag">CANDIDATE</span><h2>Professional career profile</h2><ul><li>Upload CV and create a structured profile</li><li>Add education, PVMC information, experience and skills</li><li>Select preferred sectors, roles and locations</li><li>Discover matching jobs and internships</li><li>Track saved jobs and applications</li></ul><Link href="/register" className="button button-primary">Create candidate profile</Link></article></div></section>
    <section className="section section-soft"><div className="shell"><div className="directory-top"><div><b>Latest opportunities</b><span>Sample front-end job board</span></div><div className="market-search"><input placeholder="Search role or company"/><select><option>All cities</option><option>Lahore</option><option>Faisalabad</option><option>Islamabad</option><option>Karachi</option></select></div></div><div className="job-board">{jobs.map((j,i)=><article key={j[0]}><div className="job-logo">{String(i+1).padStart(2,"0")}</div><div className="job-main"><span>{j[3]}</span><h3>{j[0]}</h3><p>{j[1]} • {j[2]}</p><div className="profile-chips"><span>{j[4]}</span><span>Profile matching</span></div></div><div className="job-apply"><small>Posted recently</small><button className="button button-primary">View & apply</button></div></article>)}</div></div></section>
    <section className="section"><div className="shell"><div className="section-heading"><span className="section-kicker">MATCHING LOGIC</span><h2>Job matching should be structured, not just a notice board.</h2><p>This part is an expansion of the current VetConnect concept: the front-end should visibly support both employer search and candidate discovery.</p></div><div className="feature-columns"><div><h3>Profile data</h3><p>Education, discipline, graduation year, PVMC status where relevant, experience, skills, certifications and CV.</p></div><div><h3>Job data</h3><p>Role, sector, location, employment type, education, experience, skills, deadline and employer profile.</p></div><div><h3>Matching</h3><p>Rank opportunities using sector, qualification, skills, location, experience and candidate preference.</p></div><div><h3>Career pipeline</h3><p>Saved jobs, applications, shortlist status, interview stage and employer communication.</p></div></div></div></section><SiteFooter /></main>;
}
